

name: kubevious-manifests-ci
on:
  push:
    branches:
      - main
    paths:
      - 'helm-chart/**'
      - 'kustomize/**'
      - '.github/workflows/kubevious-manifests-ci.yaml'
  pull_request:
    paths:
      - 'helm-chart/**'
      - 'kustomize/**'
      - '.github/workflows/kubevious-manifests-ci.yaml'
permissions:
  contents: read
jobs:
  kubevious-manifests-ci:
    runs-on: ubuntu-22.04
    timeout-minutes: 1
    steps:
      - uses: actions/checkout@v4

      - name: Validate kubernetes-manifests
        id: kubernetes-manifests-validation
        uses: kubevious/cli@v1.0.62
        with:
          manifests: kubernetes-manifests
          skip_rules: container-latest-image

      - name: Validate helm-chart
        id: helm-chart-validation
        uses: kubevious/cli@v1.0.62
        with:
          manifests: helm-chart

      - name: Validate kustomize
        id: kustomize-validation
        uses: kubevious/cli@v1.0.62
        with:
          manifests: kustomize
          skip_rules: container-latest-image
